import 'package:leak_guard/models/time_zone.dart';

class TimeZoneHelper {
  static final List<TimeZone> timeZones = [
    TimeZone.fromString("UTC [-11:00] Midway", 45),
    TimeZone.fromString("UTC [-10:00] Honolulu", 44),
    TimeZone.fromString("UTC [-09:00] Anchorage", 4),
    TimeZone.fromString("UTC [-08:00] Los Angeles", 9),
    TimeZone.fromString("UTC [-08:00] San Francisco", 9),
    TimeZone.fromString("UTC [-08:00] Tijuana", 9),
    TimeZone.fromString("UTC [-08:00] Inland Empire", 9),
    TimeZone.fromString("UTC [-07:00] Denver", 7),
    TimeZone.fromString("UTC [-07:00] Phoenix", 13),
    TimeZone.fromString("UTC [-06:00] Chicago", 6),
    TimeZone.fromString("UTC [-06:00] DallasFort Worth", 6),
    TimeZone.fromString("UTC [-06:00] Houston", 6),
    TimeZone.fromString("UTC [-06:00] Mexico City", 11),
    TimeZone.fromString("UTC [-06:00] Regina", 14),
    TimeZone.fromString("UTC [-06:00] Guadalajara", 11),
    TimeZone.fromString("UTC [-05:00] Atlanta", 12),
    TimeZone.fromString("UTC [-05:00] Boston", 12),
    TimeZone.fromString("UTC [-05:00] Miami", 12),
    TimeZone.fromString("UTC [-05:00] New York", 12),
    TimeZone.fromString("UTC [-05:00] Philadelphia", 12),
    TimeZone.fromString("UTC [-05:00] Washington DC", 12),
    TimeZone.fromString("UTC [-04:00] Halifax", 8),
    TimeZone.fromString("UTC [-04:00] Manaus", 10),
    TimeZone.fromString("UTC [-03:30] St Johns", 17),
    TimeZone.fromString("UTC [-03:00] Belo Horizonte", 16),
    TimeZone.fromString("UTC [-03:00] Buenos Aires", 5),
    TimeZone.fromString("UTC [-03:00] Rio de Janeiro", 16),
    TimeZone.fromString("UTC [-03:00] Santiago", 15),
    TimeZone.fromString("UTC [-03:00] Sao Paulo", 16),
    TimeZone.fromString("UTC [+00:00] London", 40),
    TimeZone.fromString("UTC [+01:00] Barcelona", 37),
    TimeZone.fromString("UTC [+01:00] Belgrade", 37),
    TimeZone.fromString("UTC [+01:00] Berlin", 37),
    TimeZone.fromString("UTC [+01:00] Brazzaville", 1),
    TimeZone.fromString("UTC [+01:00] Hamburg", 37),
    TimeZone.fromString("UTC [+01:00] Madrid", 37),
    TimeZone.fromString("UTC [+01:00] Milan", 37),
    TimeZone.fromString("UTC [+01:00] Munich", 37),
    TimeZone.fromString("UTC [+01:00] RhineRuhr", 37),
    TimeZone.fromString("UTC [+01:00] Rome", 37),
    TimeZone.fromString("UTC [+01:00] Sarajevo", 37),
    TimeZone.fromString("UTC [+01:00] Stuttgart", 37),
    TimeZone.fromString("UTC [+02:00] Cairo", 0),
    TimeZone.fromString("UTC [+02:00] Harare", 2),
    TimeZone.fromString("UTC [+02:00] Helsinki", 38),
    TimeZone.fromString("UTC [+03:00] Ankara", 39),
    TimeZone.fromString("UTC [+03:00] Istanbul", 39),
    TimeZone.fromString("UTC [+03:00] Jerusalem", 21),
    TimeZone.fromString("UTC [+03:00] Kuwait", 25),
    TimeZone.fromString("UTC [+03:00] Moscow", 41),
    TimeZone.fromString("UTC [+03:00] Nairobi", 3),
    TimeZone.fromString("UTC [+03:30] Tehran", 28),
    TimeZone.fromString("UTC [+04:00] Dubai", 19),
    TimeZone.fromString("UTC [+05:00] Karachi", 22),
    TimeZone.fromString("UTC [+05:00] Lahore", 22),
    TimeZone.fromString("UTC [+05:30] Ahmedabad", 24),
    TimeZone.fromString("UTC [+05:30] Bangalore", 24),
    TimeZone.fromString("UTC [+05:30] Calcutta", 24),
    TimeZone.fromString("UTC [+05:30] Chennai", 24),
    TimeZone.fromString("UTC [+05:30] Delhi", 24),
    TimeZone.fromString("UTC [+05:30] Hyderabad", 24),
    TimeZone.fromString("UTC [+05:30] Kolkata", 24),
    TimeZone.fromString("UTC [+05:30] Mumbai", 24),
    TimeZone.fromString("UTC [+05:30] Pune", 24),
    TimeZone.fromString("UTC [+05:30] Surat", 24),
    TimeZone.fromString("UTC [+05:45] Katmandu", 23),
    TimeZone.fromString("UTC [+06:30] Rangoon", 30),
    TimeZone.fromString("UTC [+07:00] Bangkok", 18),
    TimeZone.fromString("UTC [+08:00] Beijing", 27),
    TimeZone.fromString("UTC [+08:00] Changzhou", 27),
    TimeZone.fromString("UTC [+08:00] Chengdu", 27),
    TimeZone.fromString("UTC [+08:00] Chongqing", 27),
    TimeZone.fromString("UTC [+08:00] Guangzhou", 27),
    TimeZone.fromString("UTC [+08:00] Hangzhou", 27),
    TimeZone.fromString("UTC [+08:00] Hong Kong", 20),
    TimeZone.fromString("UTC [+08:00] Jinan", 27),
    TimeZone.fromString("UTC [+08:00] Nanchang", 27),
    TimeZone.fromString("UTC [+08:00] Nanjing", 27),
    TimeZone.fromString("UTC [+08:00] Perth", 35),
    TimeZone.fromString("UTC [+08:00] Qingdao", 27),
    TimeZone.fromString("UTC [+08:00] Shanghai", 27),
    TimeZone.fromString("UTC [+08:00] Shenyang", 27),
    TimeZone.fromString("UTC [+08:00] Shenzhen", 27),
    TimeZone.fromString("UTC [+08:00] Taipei", 27),
    TimeZone.fromString("UTC [+08:00] Tianjin", 27),
    TimeZone.fromString("UTC [+08:00] Wenzhou", 27),
    TimeZone.fromString("UTC [+08:00] Wuhan", 27),
    TimeZone.fromString("UTC [+08:00] Xian", 27),
    TimeZone.fromString("UTC [+08:00] Zhengzho", 27),
    TimeZone.fromString("UTC [+09:00] Nagoya", 29),
    TimeZone.fromString("UTC [+09:00] Osaka", 29),
    TimeZone.fromString("UTC [+09:00] Seoul", 26),
    TimeZone.fromString("UTC [+09:00] Tokyo", 29),
    TimeZone.fromString("UTC [+09:30] Adelaide", 31),
    TimeZone.fromString("UTC [+09:30] Darwin", 33),
    TimeZone.fromString("UTC [+10:00] Brisbane", 32),
    TimeZone.fromString("UTC [+10:00] Guam", 43),
    TimeZone.fromString("UTC [+10:00] Hobart", 34),
    TimeZone.fromString("UTC [+10:00] Sydney", 36),
    TimeZone.fromString("UTC [+13:00] Auckland", 42),
  ];

  static TimeZone getCurrentTimeZone() {
    final now = DateTime.now();
    final offset = now.timeZoneOffset.inMinutes / 60;

    return timeZones.firstWhere((tz) => tz.offset == offset,
        orElse: () => timeZones.firstWhere((tz) => tz.town == "Warsaw",
            orElse: () => timeZones.first));
  }

  static TimeZone getCurrentTimeZonebyId(int timezoneId) {
    return timeZones.firstWhere((tz) => tz.timeZoneId == timezoneId,
        orElse: () => timeZones.firstWhere((tz) => tz.town == "Warsaw",
            orElse: () => timeZones.first));
  }
}
